version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 6
    labels:
      - area/dependencies
    ignore:
      - dependency-name: io.quarkus:*
      - dependency-name: org.apache.camel:*
      - dependency-name: org.apache.camel.k:*
      - dependency-name: org.apache.camel.quarkus:*
      - dependency-name: org.apache.camel.kamelets:*
      - dependency-name: io.apicurio:*
      - dependency-name: software.amazon.awssdk:*
      - dependency-name: org.apache.maven:*
      - dependency-name: org.apache.maven.shared:*
      - dependency-name: org.apache.maven.plugin-tools:*
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris