[allowlist]
description = "Global Allowlist"

# Ignore based on any subset of the file path
paths = [
    # Ignore all example certs
#    '''\/example.*\.pem$''',

    # Ignore anything with the word funkymonkey anywhere in the path
#   '''funkymonkey''',

    # Ignore some long path
    '''src\/test\/resources\/ssl\/mongo-test.pem$''',
]

# Ignore based on any subset of the line
#regexes = [
#    # Ignore lines containing pickles
#    '''pickles''',
#]