apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: aws-kinesis-sink
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.group: "AWS"
  labels:
    camel.apache.org/kamelet.type: "sink"
    camel.apache.org/kamelet.version: "0.0.1"
spec:
  definition:
    title: "AWS Kinesis Sink"
    description: |-
      Send data to AWS Kinesis.

      The Kamelet expects the following header:

      - `partition` / `ce-partition`: to set the Kinesis partition key

      If the header won't be set the exchange ID will be used.

      The Kamelet is also able to recognize the following header:

      - `sequence-number` / `ce-sequence-number`: to set the Sequence number

      This header is optional.
    required:
      - stream
      - accessKey
      - secretKey
      - region
    type: object
    properties:
      stream:
        title: Stream Name
        description: The Kinesis stream that you want to access (needs to be created in advance)
        type: string
      accessKey:
        title: Access Key
        description: The access key obtained from AWS
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      secretKey:
        title: Secret Key
        description: The secret key obtained from AWS
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      region:
        title: AWS Region
        description: The AWS region to connect to
        type: string
        example: eu-west-1
  dependencies:
    - "camel:aws2-kinesis"
    - "camel:kamelet"
  flow:
    from:
      uri: kamelet:source
      steps:
      - choice:
          when:
          - simple: "${header[partition]}"
            steps:
            - set-header:
                name: CamelAwsKinesisPartitionKey
                simple: "${header[partition]}"
          - simple: "${header[ce-partition]}"
            steps:
            - set-header:
                name: CamelAwsKinesisPartitionKey
                simple: "${header[ce-partition]}"
          otherwise:
            steps:
            - set-property:
                name: CamelAwsKinesisPartitionKey
                simple: "${exchangeId}"
      - choice:
          when:
          - simple: "${header[sequence-number]}"
            steps:
            - set-header:
                name: CamelAwsKinesisSequenceNumber
                simple: "${header[sequence-number]}"
          - simple: "${header[ce-sequence-number]}"
            steps:
            - set-header:
                name: CamelAwsKinesisSequenceNumber
                simple: "${header[ce-sequence-number]}"
      - to:
          uri: "aws2-kinesis:{{stream}}"
          parameters:
            secretKey: "{{secretKey}}"
            accessKey: "{{accessKey}}"
            region: "{{region}}"
