apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: injector-source
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.group: "Misc"
    camel.apache.org/kamelet.version: "0.0.1"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Injector"
    description: |-
      Inject data.
    type: object
    properties:
      delay:
        title: Delay
        description: Delay
        type: string
      multiLine:
        title: Multi Line
        description: Multi Line
        type: boolean
        default: false
      showAll:
        title: Show All
        description: Show All
        type: boolean
        default: false
  dependencies:
    - "camel:timer"
    - "camel:kamelet"
    - "camel:log"
  flow:
    from:
      uri: "timer:{{routeId}}"
      parameters:
        period: "{{delay}}"
      steps:
      - set-body:
          simple: "${exchangeProperty.CamelTimerCounter}"
      - convert-body-to:
          type: "java.lang.String"
      - to:
          uri: "log:{{routeId}}"
          parameters:
            multiline: "{{multiLine}}"
            showAll: "{{showAll}}"
      - to: "kamelet:sink"
