apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: log-sink
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.group: "Misc"
  labels:
    camel.apache.org/kamelet.type: "sink"
    camel.apache.org/kamelet.version: "0.0.1"
spec:
  definition:
    title: "Log"
    description: |-
      Log payload.
    type: object
    properties:
      multiLine:
        title: Multi Line
        description: Multi Line
        type: boolean
        default: false
      showAll:
        title: Show All
        description: Show All
        type: boolean
        default: false
  dependencies:
    - "camel:log"
    - "camel:kamelet"
  flow:
    from:
      uri: "kamelet:source"
      steps:
        - to:
            uri: "log:{{routeId}}"
            parameters:
              multiline: "{{multiLine}}"
              showAll: "{{showAll}}"
