apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: managed-kafka-source
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.version: "0.0.1"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Managed Kafka Source"
    description: |-
      Receive data from Managed Kafka topics.
    required:
      - topic
    type: object
    properties:
      topic:
        title: Topic Names
        description: Comma separated list of Kafka topic names
        type: string
      autoOffsetReset:
        title: Auto Offset Reset
        description: What to do when there is no initial offset. There are 3 enums and the value can be one of latest, earliest, none
        type: string
        default: "latest"
      consumerGroup:
        title: Consumer Group
        description: A string that uniquely identifies the group of consumers to which this source belongs
        type: string
        example: "my-group-id"
  dependencies:
    - "camel:kafka"
    - "camel:kamelet"
  flow:
    from:
      uri: "kafka:{{topic}}"
      parameters:
        brokers: "{{?bootstrapServers}}"
        securityProtocol: "{{securityProtocol:SASL_SSL}}"
        saslMechanism: "{{saslMechanism:PLAIN}}"
        saslJaasConfig: "org.apache.kafka.common.security.plain.PlainLoginModule required username='{{user}}' password='{{password}}';"
        autoOffsetReset: "{{autoOffsetReset:latest}}"
        groupId: "{{?consumerGroup}}"
      steps:
      - to: "kamelet:sink"
