apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: managed-kafka-sink
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.version: "0.0.1"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "Managed Kafka Sink"
    description: |-
      Send data to Managed Kafka topics.
    required:
      - topic
    properties:
      topic:
        title: Topic names
        description: Comma separated list of Kafka topic names
        type: string
  dependencies:
    - mvn:org.apache.kafka:kafka-clients:2.6.0
  flow:
    from:
      uri: "kamelet:source"
      steps:
        - to:
            uri: "kafka:{{topic}}"
            parameters:
              brokers: "{{bootstrapServers}}"
              securityProtocol: "{{securityProtocol:SASL_SSL}}"
              saslMechanism: "{{saslMechanism:PLAIN}}"
              saslJaasConfig: "org.apache.kafka.common.security.plain.PlainLoginModule required username='{{user}}' password='{{password}}';"
