apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: mariadb-source
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.group: "AWS"
  labels:
    camel.apache.org/kamelet.type: "source"
    camel.apache.org/kamelet.version: "0.0.1"
spec:
  definition:
    title: "MariaDB Source"
    description: |-
      Query data from a MariaDB Database.

      In you KameletBinding file you'll need to explicitly declare the MariaDB Server driver dependency in spec->integration->dependencies
      
      - "mvn:org.mariadb.jdbc:mariadb-java-client:<version>"
    required:
      - serverName
      - username
      - password
      - query
      - databaseName
    type: object
    properties:
      serverName:
        title: Server Name
        description: Server Name for the data source
        type: string
        example: localhost
      port:
        title: Port
        description: Server Port for the data source
        type: string
        default: 3306
      username:
        title: Username
        description: The username to use for accessing a secured MariaDB Database
        type: string
      password:
        title: Password
        description: The password to use for accessing a secured MariaDB Database
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      query:
        title: Query
        description: The Query to execute against the MariaDB Database
        type: string
        example: 'INSERT INTO accounts (username,city) VALUES (:#username,:#city)'
      databaseName:
        title: Database Name
        description: The Database Name we are pointing
        type: string
      consumedQuery:
        title: Consumed Query
        description: A query to run on a tuple consumed
        type: string
        example: 'DELETE FROM accounts where user_id = :#user_id'
  types:
    in:
      mediaType: application/json
  dependencies:
  - "camel:jackson"
  - "camel:kamelet"
  - "camel:sql"
  - "mvn:org.apache.commons:commons-dbcp2:2.8.0"
  flow:
    beans:
      - name: dsBean
        type: "#class:org.apache.commons.dbcp2.BasicDataSource"
        property:
          - key: username
            value: '{{username}}'
          - key: password
            value: '{{password}}'
          - key: url
            value: 'jdbc:mariadb://{{serverName}}:{{port}}/{{databaseName}}'
          - key: driverClassName
            value: 'org.mariadb.jdbc.Driver'
    from:
      uri: "sql:{{query}}"
      parameters:
        dataSource: "#bean:{{dsBean}}"
        onConsume: "{{?consumedQuery}}"
      steps:
      - marshal:
          json: 
            library: Jackson
      - to: "kamelet:sink"
