apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: mariadb-sink
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.group: "AWS"
  labels:
    camel.apache.org/kamelet.type: "sink"
    camel.apache.org/kamelet.version: "0.0.1"
spec:
  definition:
    title: "MariaDB Sink"
    description: |-
      Send data to a MariaDB Database.

      This Kamelet expects a JSON as body. The mapping between the JSON fields and parameters is done by key, so if you have the following query:

      'INSERT INTO accounts (username,city) VALUES (:#username,:#city)'

      The Kamelet needs to receive as input something like:

      '{ "username":"oscerd", "city":"Rome"}'
    required:
      - serverName
      - username
      - password
      - query
      - databaseName
    type: object
    properties:
      serverName:
        title: Server Name
        description: Server Name for the data source
        type: string
        example: localhost
      port:
        title: Port
        description: Server Port for the data source
        type: string
        default: 3306
      username:
        title: Username
        description: The username to use for accessing a secured MariaDB Database
        type: string
      password:
        title: Password
        description: The password to use for accessing a secured MariaDB Database
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      query:
        title: Query
        description: The Query to execute against the MariaDB Database
        type: string
        example: 'INSERT INTO accounts (username,city) VALUES (:#username,:#city)'
      databaseName:
        title: Database Name
        description: The Database Name we are pointing
        type: string
  types:
    in:
      mediaType: application/json
  dependencies:
  - "camel:jackson"
  - "camel:kamelet"
  - "camel:sql"
  - "mvn:org.apache.commons:commons-dbcp2:2.8.0"
  - "mvn:org.mariadb.jdbc:mariadb-java-client:2.7.3"
  flow:
    beans:
      - name: dsBean
        type: "#class:org.apache.commons.dbcp2.BasicDataSource"
        property:
          - key: username
            value: '{{username}}'
          - key: password
            value: '{{password}}'
          - key: url
            value: 'jdbc:mariadb://{{serverName}}:{{port}}/{{databaseName}}'
          - key: driverClassName
            value: 'org.mariadb.jdbc.Driver'
    from:
      uri: "kamelet:source"
      steps:
      - unmarshal:
          json: 
            library: Jackson
      - to: 
          uri: "sql:{{query}}"
          parameters:
            dataSource: "#bean:{{dsBean}}"
