apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: cos-azure-storage-blob-source
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.version: "${cos.kamelets.version}"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Azure Storage Blob Source"
    description: |-
      Consume files from Azure Storage Blob.

      Two headers will be duplicated with different names for clarity at sink level, CamelAzureStorageBlobETag will be duplicated into azure.storage.blob.e.tag and CamelAzureStorageBlobBlobSize will be duplicated in azure.storage.blob.blob.size
    required:
      - accountName
      - containerName
      - accessKey
    type: object
    properties:
      accountName:
        title: Account Name
        description: The Azure Storage Blob account name.
        type: string
        x-descriptors:
          - urn:camel:group:credentials
      containerName:
        title: Container Name
        description: The Azure Storage Blob container name.
        type: string
      accessKey:
        title: Access Key
        description: The Azure Storage Blob access key.
        type: string
        format: password
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:password
          - urn:camel:group:credentials
      delay:
        title: Delay
        description: The number of milliseconds before the next poll of the selected blob.
        type: integer
        default: 500
      deleteAfterRead:
        title: "Auto-delete Blob"
        description: "Specifies to delete blob after consuming them."
        type: boolean
        default: false
  dependencies:
    - "camel:azure-storage-blob"
    - "camel:kamelet"
    - "camel:core"
    - "camel:timer"
  template:
    from:
      uri: "azure-storage-blob:{{accountName}}/{{containerName}}"
      parameters:
        accessKey: "{{accessKey}}"
        credentialType: "{{credentialType}}"
        delay: "{{delay}}"
      steps:
        - to: "kamelet:sink"
        - choice:
            precondition: true
            when:
              - simple: '${properties:deleteAfterRead:false}'
                steps:
                  - to:
                      uri: "azure-storage-blob:{{accountName}}/{{containerName}}"
                      parameters:
                        operation: "deleteBlob"
                        accessKey: "{{accessKey}}"
                        credentialType: "SHARED_ACCOUNT_KEY"

