FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5

COPY kubernetes/manifests/base/connectors /etc/connectors

LABEL name="cos-fleet-catalog-camel" \
      vendor="Red Hat" \
      summary="CosFleetCatalogCamel" \
      description="Kafka Connector Service Catalog Camel"
