apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: cos-jsonpath-rename-action
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.group: "Transform"
    camel.apache.org/kamelet.version: "${cos.kamelets.version}"
  labels:
    camel.apache.org/kamelet.type: "action"
spec:
  definition:
    title: "Transform with JsonPath"
    description: |-
      TBD
    type: object
    required:
      - expression
    properties:
      expression:
        title: Expression
        description: Expression
        type: string
      key:
        title: Key
        description: Key
        type: string
      newKey:
        title: NewKey
        description: NewKey
        type: string
  dependencies:
    - "camel:log"
    - "camel:kamelet"
  template:
    beans:
      - name: "action"
        type: "#class: org.bf2.cos.connector.camel.actions.JsonPathProcessor"
        properties:
          action: "SET"
          expression: '{{expression}}'
          key: '{{key}}'
          newKey: '{{newKey}}'
    from:
      uri: kamelet:source
      steps:
        - process:
            ref: "{{action}}"
