apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: cos-telegram-source
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.version: "${cos.kamelets.version}"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Telegram Source"
    description: |-
      Receive all messages that people send to your Telegram bot.

      To create a bot, contact the @botfather account by using the Telegram app.

      The source attaches the following header to the messages:

      - `chat-id` / `ce-chatid`: The ID of the chat where the message comes from.

    required:
      - authorizationToken
    type: object
    properties:
      authorizationToken:
        title: Token
        description: "The token to access your bot on Telegram. You you can obtain it from the Telegram @botfather."
        type: string
        format: password
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
        - urn:camel:group:credentials
  types:
    out:
      mediaType: application/json
  dependencies:
    - "camel:jackson"
    - "camel:kamelet"
    - "camel:telegram"
    - "camel:core"
  template:
    from:
      uri: telegram:bots
      parameters:
        authorizationToken: "{{authorizationToken}}"
      steps:
      - set-header:
          name: chat-id
          simple: "${header[CamelTelegramChatId]}"
      - set-header:
          name: ce-chatid
          simple: "${header[CamelTelegramChatId]}"
      - marshal:
          json: {}
      - to: "kamelet:sink"
