apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: cos-azure-eventhubs-sink
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.version: "${cos.kamelets.version}"
  labels:
    camel.apache.org/kamelet.type: "sink"
spec:
  definition:
    title: "Azure Eventhubs Sink"
    description: |-
      Send Events to Azure Eventhubs.

      The Kamelet is able to understand the following headers to be set:

      - `partition` / `ce-partition`: as the time to live of the message in the queue.

      If the header won't be set then the partition will be assigned by Eventhubs
    required:
      - namespaceName
      - eventhubName
      - sharedAccessName
      - sharedAccessKey
    type: object
    properties:
      namespaceName:
        title: Eventhubs Namespace
        description: The eventhubs namespace
        type: string
      eventhubName:
        title: Eventhubs Name
        description: The eventhub name
        type: string
      sharedAccessName:
        title: Share Access Name
        description: EventHubs SAS key name
        type: string
        x-descriptors:
          - urn:camel:group:credentials
      sharedAccessKey:
        title: Share Access Key
        description: The key for EventHubs SAS key name
        type: string
        format: password
        x-descriptors:
          - urn:alm:descriptor:com.tectonic.ui:password
          - urn:camel:group:credentials
  dependencies:
    - "camel:core"
    - "camel:azure-eventhubs"
    - "camel:kamelet"
  template:
    from:
      uri: "kamelet:source"
      steps:
        - choice:
            when:
              - simple: "${header[partition]}"
                steps:
                  - set-header:
                      name: CamelAzureEventHubsPartitionId
                      simple: "${header[partition]}"
              - simple: "${header[ce-partition]}"
                steps:
                  - set-header:
                      name: CamelAzureEventHubsPartitionId
                      simple: "${header[ce-partition]}"
        - bean:
            beanType: "org.bf2.cos.connector.camel.azure.AzureHeadersProcessor"
        - removeHeaders:
            pattern: "kafka.*"
        - to:
            uri: "azure-eventhubs://{{namespaceName}}/{{eventhubName}}"
            parameters:
              sharedAccessName: "{{sharedAccessName}}"
              sharedAccessKey: "{{sharedAccessKey}}"