name: Update Manifest

on:
  workflow_call:
    inputs:
      overlay:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Set versions
        run: |
          export C_VERSION="${GITHUB_REF_NAME#v}" 
          export C_REVISION="${GITHUB_SHA}" 

          echo "CONNECTORS_VERSION=${C_VERSION}" >> $GITHUB_ENV
          echo "CONNECTORS_REVISION=${C_REVISION}" >> $GITHUB_ENV
          echo "CONNECTORS_RELEASE=${C_VERSION}-${C_REVISION}" >> $GITHUB_ENV

      - name: "Checkout cos-manifests project"
        uses: actions/checkout@v2
        with:
          repository: bf2fc6cc711aee1a0c2a/cos-manifests
          token: ${{ secrets.token }}
          ref: main

      - name: "Update Kustomize overlay ${{ inputs.overlay }}"
        uses: mikefarah/yq@master
        env:
          OVERLAY_PATH: kustomize/overlays/${{ inputs.overlay }}/control-plane/cos-fleet-catalog-camel
        with:
          cmd: |
            yq -i '.images[0].newTag = strenv(CONNECTORS_RELEASE)' ${OVERLAY_PATH}/kustomization.yaml

      - name: "Create PR for ${{ inputs.overlay }}"
        env:
          OVERLAY_PATH: kustomize/overlays/${{ inputs.overlay }}/control-plane/cos-fleet-catalog-camel
          BRANCH_NAME: "cos-fleet-catalog-camel.${{ inputs.overlay }}.${{ env.CONNECTORS_RELEASE }}"
          GH_TOKEN: ${{ secrets.token }}
        run: |
          echo ""
          echo "tag      : ${{ github.ref_name }}"
          echo "version  : ${CONNECTORS_VERSION}"
          echo "revision : ${CONNECTORS_REVISION}"
          echo "release  : ${CONNECTORS_RELEASE}"
          echo "branch   : ${BRANCH_NAME}"
          echo ""

          git config user.email "mas-connectors@redhat.com" 
          git config user.name "mas-connectors"

          git checkout -b ${BRANCH_NAME}
          git add ${OVERLAY_PATH}
          git commit -m "Update cos-fleet-catalog-camel kustomization images for overlay ${{ inputs.overlay }}" ${OVERLAY_PATH}
          git reset --hard
          git push -u origin ${BRANCH_NAME}

          # GH CLI can't find the branch on remote... needs some time :)
          sleep 15

          gh config set prompt disabled

          gh pr create \
            --fill \
            --base main \
            --title "chore(kustomize): update cos-fleet-catalog-camel kustomization images overlay ${{ inputs.overlay }}" \
            --body "sha: ${{ github.sha }}, overlay: ${{ inputs.overlay }}, tag: ${{ github.ref_name }}"
